---
- name: Ensure web group is present
  group:
    name: "{{ remote_web_user }}"
    state: present

- name: Create web user
  user:
    name: "{{ remote_web_user }}"
    group: "{{ remote_web_user }}"
    password: "{{ remote_web_user_password }}"
    shell: /bin/bash
    update_password: always
    state: present

- name: Add authorized key
  authorized_key:
    user: "{{ remote_web_user }}"
    key: "{{ web_user_ssh_public_key }}"